# Site settings
title: Règlements de comptes à Marseille
email: 
description: > # this means to ignore newlines until "baseurl:"
  Retour sur les cas survenus en 2015 par les étudiants de l'Ecole de Journalisme de Sciences Po.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://reglementsdecomptes.github.io" # the base hostname & protocol for your site
# twitter_username: jekyllrb
github_username:  reglementsdecomptes

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts" # previously `post` in Jekyll 2.2.
    values:
      layout: "default"

# Build settings
markdown: kramdown
exclude: [vendor]